-- Loaded by backend/tests/conftest.py after TRUNCATE (not part of supabase db seed).
INSERT INTO organizations (id, name, slug, created_at) VALUES ('0195f2c0-89aa-7d6d-bb34-7f3b3f69c001', 'Supply Yard', 'supply-yard', NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, slug = EXCLUDED.slug;
INSERT INTO departments (id, name, code, description, sku_count, organization_id, created_at) VALUES ('0195f2c0-89ac-7f42-8b11-000000000001', 'Hardware', 'HDW', 'Hardware dept', 0, '0195f2c0-89aa-7d6d-bb34-7f3b3f69c001', NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, code = EXCLUDED.code, description = EXCLUDED.description, sku_count = EXCLUDED.sku_count, organization_id = EXCLUDED.organization_id;
-- Matches tests.helpers.auth.SEEDED_JOB_ID — material request process resolves UUID to job row.
INSERT INTO jobs (id, code, name, billing_entity_id, status, service_address, organization_id, created_at, updated_at) VALUES ('019d44b8-a763-757a-9d68-a576ca2044c3', 'RR-2026-001', 'Pytest seeded job', NULL, 'active', '1200 Mountain View Dr', '0195f2c0-89aa-7d6d-bb34-7f3b3f69c001', NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, service_address = EXCLUDED.service_address, organization_id = EXCLUDED.organization_id, updated_at = EXCLUDED.updated_at;
INSERT INTO users (id, email, name, role, is_active, organization_id, created_at) VALUES ('0195f2c0-89ab-7a10-8a01-000000000001', 'admin@supplyyard.com', 'Marcus Chen', 'admin', TRUE, '0195f2c0-89aa-7d6d-bb34-7f3b3f69c001', NOW()) ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, name = EXCLUDED.name, role = EXCLUDED.role, is_active = EXCLUDED.is_active, organization_id = EXCLUDED.organization_id;
INSERT INTO users (id, email, name, role, is_active, organization_id, created_at) VALUES ('0195f2c0-89ab-7a10-8a01-000000000004', 'dev@supply-yard.local', 'Dev Admin', 'admin', TRUE, '0195f2c0-89aa-7d6d-bb34-7f3b3f69c001', NOW()) ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, name = EXCLUDED.name, role = EXCLUDED.role, is_active = EXCLUDED.is_active, organization_id = EXCLUDED.organization_id;
INSERT INTO users (id, email, name, role, company, is_active, organization_id, created_at) VALUES ('0195f2c0-89ab-7a10-8a01-000000000003', 'sarah@summitpm.com', 'Sarah Okafor', 'contractor', 'Summit Property Group', TRUE, '0195f2c0-89aa-7d6d-bb34-7f3b3f69c001', NOW()) ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, name = EXCLUDED.name, role = EXCLUDED.role, company = EXCLUDED.company, is_active = EXCLUDED.is_active, organization_id = EXCLUDED.organization_id;
INSERT INTO users (id, email, name, role, is_active, organization_id, created_at) VALUES ('0195f2c0-89ab-7a10-8a01-0bad00000001', 'onboard-admin@test.com', 'Onboard Admin', 'admin', TRUE, NULL, NOW()) ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, name = EXCLUDED.name, role = EXCLUDED.role, is_active = EXCLUDED.is_active, organization_id = EXCLUDED.organization_id;
INSERT INTO users (id, email, name, role, is_active, organization_id, created_at) VALUES ('0195f2c0-89ab-7a10-8a01-0bad00000002', 'onboard-ctr@test.com', 'Onboard Contractor', 'contractor', TRUE, NULL, NOW()) ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, name = EXCLUDED.name, role = EXCLUDED.role, is_active = EXCLUDED.is_active, organization_id = EXCLUDED.organization_id;
